PANDARIA: Fix show unauthorized when group member to get the monitor data
cnrancher/prometheus-auth pull request #10
Opened 2020-11-12 08:27 UTC by GGGitBoy

在通过方式 ` r.Header["Key"] ` 获取请求头数组的时key需要遵循大驼峰的规范，否则返回的为nil

具体查看 https://github.com/golang/go/issues/34799

golang 1.14 开始支持  r.Header.Values(key string) 方法获取请求头 map 对应的数组，但是当前 repo 还是golang 1.13。所以暂时修改 key `X-RANCHER-GROUP` 的命名

**Relate issue：**
https://github.com/cnrancher/pandaria/issues/1187

2020-11-13 07:29 UTC, aiwantaozi commented
在代码旁边加一下comment和issue链接，其他没什么问题

2020-11-16 00:57 UTC, orangedeng requested changes
把user header key一起改了，不然只是为了规避问题只改group header有点奇怪

2020-11-16 05:01 UTC, GGGitBoy commented
@orangedeng Update!

2020-11-18 08:00 UTC, aiwantaozi reviewed
PR本身没什么问题，但是用户升级了rancher server之后，是不是监控就看不到数据了？是不是监控也需要升级，这个升级能否接受。

2020-11-18 11:04 UTC, GGGitBoy commented
`r.Header.Get`是大小写不敏感的，有试过使用不同大小写的X-RANCHER-USER请求头，能获取到数据

2020-11-18 14:53 UTC, guangbochen commented
@orangedeng @aiwantaozi can u please help to review it again, thanks

2020-11-19 02:36 UTC, aiwantaozi approved these changes

2020-11-19 05:29 UTC, orangedeng approved these changes
LGTM

2020-11-19 05:30 UTC, merged